### ISSUE TITLE
Where can I find versioned Docker images?

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/o2k-connector#2]
I'm looking to use the o2k connector, but I can't find the **Versioned** Docker images anywhere - there is no link on the README, could you advice me as to where to find them?

A registry exists here: https://registry.hub.docker.com/r/rdlabengpa/o2k-connector - but I can see no images.

**Comment by manfredipist** [comment]
Hi @jason-fox ,
here's the link to the versioned docker image

https://hub.docker.com/r/rdlabengpa/o2k-connector/tags
